// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4pa6xkQzB7dAPoSTmJgvZjY-K5Taq1pA',
    appId: '1:1028500808003:web:cd2790978bd668f825cff6',
    messagingSenderId: '1028500808003',
    projectId: 'iti-lab1-12661',
    authDomain: 'iti-lab1-12661.firebaseapp.com',
    storageBucket: 'iti-lab1-12661.firebasestorage.app',
    measurementId: 'G-9Y9CQWNM12',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKkXzJPm5LTm7Q6fnONdUTPoXK09rGBwc',
    appId: '1:1028500808003:android:c7203b2f411b9b3925cff6',
    messagingSenderId: '1028500808003',
    projectId: 'iti-lab1-12661',
    storageBucket: 'iti-lab1-12661.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC4pa6xkQzB7dAPoSTmJgvZjY-K5Taq1pA',
    appId: '1:1028500808003:web:51933d757656d8c725cff6',
    messagingSenderId: '1028500808003',
    projectId: 'iti-lab1-12661',
    authDomain: 'iti-lab1-12661.firebaseapp.com',
    storageBucket: 'iti-lab1-12661.firebasestorage.app',
    measurementId: 'G-VR7PP5JTCE',
  );
}
